// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remy/pkg/ent/event"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (ec *EventCreate) SetTitle(s string) *EventCreate {
	ec.mutation.SetTitle(s)
	return ec
}

// SetStart sets the "start" field.
func (ec *EventCreate) SetStart(t time.Time) *EventCreate {
	ec.mutation.SetStart(t)
	return ec
}

// SetEnd sets the "end" field.
func (ec *EventCreate) SetEnd(t time.Time) *EventCreate {
	ec.mutation.SetEnd(t)
	return ec
}

// SetXPos sets the "xPos" field.
func (ec *EventCreate) SetXPos(f float32) *EventCreate {
	ec.mutation.SetXPos(f)
	return ec
}

// SetYPos sets the "yPos" field.
func (ec *EventCreate) SetYPos(f float32) *EventCreate {
	ec.mutation.SetYPos(f)
	return ec
}

// SetID sets the "id" field.
func (ec *EventCreate) SetID(i int64) *EventCreate {
	ec.mutation.SetID(i)
	return ec
}

// Mutation returns the EventMutation object of the builder.
func (ec *EventCreate) Mutation() *EventMutation {
	return ec.mutation
}

// Save creates the Event in the database.
func (ec *EventCreate) Save(ctx context.Context) (*Event, error) {
	var (
		err  error
		node *Event
	)
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, ec.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Event)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EventMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EventCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EventCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EventCreate) check() error {
	if _, ok := ec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Event.title"`)}
	}
	if _, ok := ec.mutation.Start(); !ok {
		return &ValidationError{Name: "start", err: errors.New(`ent: missing required field "Event.start"`)}
	}
	if _, ok := ec.mutation.End(); !ok {
		return &ValidationError{Name: "end", err: errors.New(`ent: missing required field "Event.end"`)}
	}
	if _, ok := ec.mutation.XPos(); !ok {
		return &ValidationError{Name: "xPos", err: errors.New(`ent: missing required field "Event.xPos"`)}
	}
	if _, ok := ec.mutation.YPos(); !ok {
		return &ValidationError{Name: "yPos", err: errors.New(`ent: missing required field "Event.yPos"`)}
	}
	return nil
}

func (ec *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (ec *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: event.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: event.FieldID,
			},
		}
	)
	_spec.OnConflict = ec.conflict
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ec.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := ec.mutation.Start(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: event.FieldStart,
		})
		_node.Start = value
	}
	if value, ok := ec.mutation.End(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: event.FieldEnd,
		})
		_node.End = value
	}
	if value, ok := ec.mutation.XPos(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat32,
			Value:  value,
			Column: event.FieldXPos,
		})
		_node.XPos = value
	}
	if value, ok := ec.mutation.YPos(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat32,
			Value:  value,
			Column: event.FieldYPos,
		})
		_node.YPos = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
//
func (ec *EventCreate) OnConflict(opts ...sql.ConflictOption) *EventUpsertOne {
	ec.conflict = opts
	return &EventUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (ec *EventCreate) OnConflictColumns(columns ...string) *EventUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertOne{
		create: ec,
	}
}

type (
	// EventUpsertOne is the builder for "upsert"-ing
	//  one Event node.
	EventUpsertOne struct {
		create *EventCreate
	}

	// EventUpsert is the "OnConflict" setter.
	EventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *EventUpsert) SetTitle(v string) *EventUpsert {
	u.Set(event.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsert) UpdateTitle() *EventUpsert {
	u.SetExcluded(event.FieldTitle)
	return u
}

// SetStart sets the "start" field.
func (u *EventUpsert) SetStart(v time.Time) *EventUpsert {
	u.Set(event.FieldStart, v)
	return u
}

// UpdateStart sets the "start" field to the value that was provided on create.
func (u *EventUpsert) UpdateStart() *EventUpsert {
	u.SetExcluded(event.FieldStart)
	return u
}

// SetEnd sets the "end" field.
func (u *EventUpsert) SetEnd(v time.Time) *EventUpsert {
	u.Set(event.FieldEnd, v)
	return u
}

// UpdateEnd sets the "end" field to the value that was provided on create.
func (u *EventUpsert) UpdateEnd() *EventUpsert {
	u.SetExcluded(event.FieldEnd)
	return u
}

// SetXPos sets the "xPos" field.
func (u *EventUpsert) SetXPos(v float32) *EventUpsert {
	u.Set(event.FieldXPos, v)
	return u
}

// UpdateXPos sets the "xPos" field to the value that was provided on create.
func (u *EventUpsert) UpdateXPos() *EventUpsert {
	u.SetExcluded(event.FieldXPos)
	return u
}

// AddXPos adds v to the "xPos" field.
func (u *EventUpsert) AddXPos(v float32) *EventUpsert {
	u.Add(event.FieldXPos, v)
	return u
}

// SetYPos sets the "yPos" field.
func (u *EventUpsert) SetYPos(v float32) *EventUpsert {
	u.Set(event.FieldYPos, v)
	return u
}

// UpdateYPos sets the "yPos" field to the value that was provided on create.
func (u *EventUpsert) UpdateYPos() *EventUpsert {
	u.SetExcluded(event.FieldYPos)
	return u
}

// AddYPos adds v to the "yPos" field.
func (u *EventUpsert) AddYPos(v float32) *EventUpsert {
	u.Add(event.FieldYPos, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(event.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *EventUpsertOne) UpdateNewValues() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(event.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Event.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *EventUpsertOne) Ignore() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertOne) DoNothing() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreate.OnConflict
// documentation for more info.
func (u *EventUpsertOne) Update(set func(*EventUpsert)) *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *EventUpsertOne) SetTitle(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateTitle() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTitle()
	})
}

// SetStart sets the "start" field.
func (u *EventUpsertOne) SetStart(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetStart(v)
	})
}

// UpdateStart sets the "start" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateStart() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateStart()
	})
}

// SetEnd sets the "end" field.
func (u *EventUpsertOne) SetEnd(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetEnd(v)
	})
}

// UpdateEnd sets the "end" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateEnd() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEnd()
	})
}

// SetXPos sets the "xPos" field.
func (u *EventUpsertOne) SetXPos(v float32) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetXPos(v)
	})
}

// AddXPos adds v to the "xPos" field.
func (u *EventUpsertOne) AddXPos(v float32) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddXPos(v)
	})
}

// UpdateXPos sets the "xPos" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateXPos() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateXPos()
	})
}

// SetYPos sets the "yPos" field.
func (u *EventUpsertOne) SetYPos(v float32) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetYPos(v)
	})
}

// AddYPos adds v to the "yPos" field.
func (u *EventUpsertOne) AddYPos(v float32) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddYPos(v)
	})
}

// UpdateYPos sets the "yPos" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateYPos() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateYPos()
	})
}

// Exec executes the query.
func (u *EventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	builders []*EventCreate
	conflict []sql.ConflictOption
}

// Save creates the Event entities in the database.
func (ecb *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Event, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EventCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
//
func (ecb *EventCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventUpsertBulk {
	ecb.conflict = opts
	return &EventUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (ecb *EventCreateBulk) OnConflictColumns(columns ...string) *EventUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertBulk{
		create: ecb,
	}
}

// EventUpsertBulk is the builder for "upsert"-ing
// a bulk of Event nodes.
type EventUpsertBulk struct {
	create *EventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(event.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *EventUpsertBulk) UpdateNewValues() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(event.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *EventUpsertBulk) Ignore() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertBulk) DoNothing() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreateBulk.OnConflict
// documentation for more info.
func (u *EventUpsertBulk) Update(set func(*EventUpsert)) *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *EventUpsertBulk) SetTitle(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateTitle() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTitle()
	})
}

// SetStart sets the "start" field.
func (u *EventUpsertBulk) SetStart(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetStart(v)
	})
}

// UpdateStart sets the "start" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateStart() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateStart()
	})
}

// SetEnd sets the "end" field.
func (u *EventUpsertBulk) SetEnd(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetEnd(v)
	})
}

// UpdateEnd sets the "end" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateEnd() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEnd()
	})
}

// SetXPos sets the "xPos" field.
func (u *EventUpsertBulk) SetXPos(v float32) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetXPos(v)
	})
}

// AddXPos adds v to the "xPos" field.
func (u *EventUpsertBulk) AddXPos(v float32) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddXPos(v)
	})
}

// UpdateXPos sets the "xPos" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateXPos() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateXPos()
	})
}

// SetYPos sets the "yPos" field.
func (u *EventUpsertBulk) SetYPos(v float32) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetYPos(v)
	})
}

// AddYPos adds v to the "yPos" field.
func (u *EventUpsertBulk) AddYPos(v float32) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddYPos(v)
	})
}

// UpdateYPos sets the "yPos" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateYPos() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateYPos()
	})
}

// Exec executes the query.
func (u *EventUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
