services:
#-----------------------------------------------------------------
  mysql-server:
    image: mysql:latest
    container_name: mysql-sample
    ports: 
      - 13306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    env_file: ./.env

#-----------------------------------------------------------------
  sample:
    build:
      context: .
      dockerfile: backend/build/Dockerfile
    container_name: sample
    environment:
      DB_HOST: mysql-server
    ports:
      - 50051:50051
    restart: always
    depends_on:
      - mysql-server
    env_file: ./.env
    entrypoint: ["/app/main"]