services:
  #-----------------------------------------------------------------
  # mysql-server:
  #   image: mysql:latest
  #   container_name: mysql-server
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db:/var/lib/mysql
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     MYSQL_DATABASE: "remy"
  #     MYSQL_ROOT_PASSWORD: "P@ssw0rd"

  #-----------------------------------------------------------------


  envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: hello_lupin
    container_name: Greeter
    ports:
      - ${PORT:-50054}:50053
  remy:
    build:
      context: .
      dockerfile: backend/build/Dockerfile
    container_name: remy
    # environment:
    #   DB_HOST: mysql-server

    ports:
      - 50051:50051
      - 50052:50052
    restart: always
    # depends_on:
    #   - mysql-server
    entrypoint: [ "/app/main" ]

volumes:
  db:
    driver: local
networks:
  samenet:
    driver: bridge
