services:
  #-----------------------------------------------------------------
  mysql-server:
    image: mysql:latest
    container_name: mysql-sample
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"

  #-----------------------------------------------------------------
  sample:
    build:
      context: .
      dockerfile: backend/build/Dockerfile
    container_name: sample
    environment:
      DB_HOST: mysql-server
    ports:
      - 50051:50051
    restart: always
    depends_on:
      - mysql-server
    entrypoint: [ "/app/main" ]

volumes:
  db:
    driver: local
